name: Super=Lint
on: push
jobs:
  super-lint:
    name: LInt code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKENS: ${{secrets.GITHUB_TOKEN}}
